name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # atau branch lain yang lo gunakan

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies with legacy-peer-deps
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # pastikan ini sesuai dengan folder output hasil build Next.js
